version: '3'
services:
  event-booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: event-booking-service:1.0
    restart: always
    container_name: event-booking-service
    networks:
      - event_b_network
    ports:
      - "8086:8086"

networks:
  event_b_network:
    external: true
    driver: bridge
