apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: event-booking-hpa-v4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-booking-rocket-001
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"

#kubectl apply -f event-booking-deployment.yaml
#kubectl apply -f event-booking-service.yaml
#kubectl apply -f event-booking-hpa-v1.yaml
#kubectl delete -f event-booking-hpa-v1.yaml
#kubectl get hpa
#kubectl get hpa event-booking-hpa-v1
