spring:
  application:
    name: event-booking

app:
  security:
    encryption:
      key: bf538f592a721cfed601da884f4a03cf294cf4507b2e40b11058950407ef3cfa
  opt:
    expire:
      time: 600
  mail:
    sender:
      name: Musala Soft
      email: isaiahomame@gmail.com