server:
  port: 8080
  host: localhost
  servlet:
    contextPath: /event-booking

spring:
  application:
    name: event-booking
  kafka:
    consumer:
      group-id: event-booking-group-id
    producer:
      bootstrap-servers: http://event_booking_kafka:19092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://event_booking_mysql:3306/event_booking_container?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: eVen20tBoo_ING_24
    jmx:
      default-domain: event-booking
  liquibase:
    contexts: dev
    url: jdbc:mysql://event_booking_mysql:3306/event_booking_container?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    user: root
    password: eVen20tBoo_ING_24
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    dropFirst: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none #none, create, create-drop, update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com
    username: omameazy@gmail.com
    #Put in Docker Environment Variable File
    port: 465
    password: lrtciqzoohrtkmuq
    #Put in Docker Environment Variable File
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          ssl:
            enable: true
          auth: true
        transport:
          protocol: smtp
        debug: true
    protocol: smtp
    test-connection: false

app:
  api:
    auth:
      url: http://${server.host}:${server.port}${server.servlet.contextPath}/api/v1/auth
  security:
    encryption:
      key: bf538f592a721cfed601da884f4a03cf294cf4507b2e40b11058950407ef3cfa
  opt:
    expire:
      time: 600
  mail:
    sender:
      name: Event Booking Ltd.
      email: omameazy@gmail.com
  jwt:
    authorities:
      key: roles
    expirationDateInMs: 86400000
    header:
      string: Authorization
    jwtCookieName: event-booking
    jwtRefreshCookieName: event-booking-refresh
    refreshExpiration: 8640
    refreshExpirationDateInMs: 8640
    signing:
      key: 837f5b3ae7ccd9498d989595fab6da25b0ca2fbda6424b2d8d0bd24f43e39cd1
    token:
      prefix: Bearer
      validity: 100
